import PublicLayout from '@/Layouts/PublicLayout';
import { Head, useForm } from '@inertiajs/react';

const statusLabels = { pending: 'Pedido recibido', paid: 'Pago confirmado', shipped: 'En camino', delivered: 'Entregado', failed: 'Pago fallido' };

export default function OrderTracking({ auth, order }) {
    const { data, setData, post, processing } = useForm({ buy_order: '', email: '' });
    const submit = (event) => { event.preventDefault(); post(route('tracking.search')); };
    return (
        <PublicLayout auth={auth}><Head><title>Seguimiento de pedido | Melkerven</title></Head>
            <section className="relative min-h-[80vh] overflow-hidden bg-cloud-50 py-16 sm:py-20"><div className="public-network absolute inset-0 opacity-60" /><div className="section-shell relative z-10 max-w-4xl"><div className="public-eyebrow">Seguimiento</div><h1 className="mt-6 text-5xl font-semibold tracking-[-.06em] text-ink-950 sm:text-6xl">Estado de su <span className="text-signal-600">pedido.</span></h1><p className="mt-5 max-w-2xl text-lg leading-8 text-ink-600">Ingrese el número de orden y el correo de compra para consultar el avance.</p>
                <form onSubmit={submit} className="mt-10 rounded-3xl border border-white/80 bg-white p-6 shadow-[0_18px_48px_rgba(31,62,82,.10)] sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><div><label htmlFor="order-number" className="mb-2 block text-[10px] font-bold uppercase tracking-widest text-ink-500">Número de orden</label><input id="order-number" value={data.buy_order} onChange={(event) => setData('buy_order', event.target.value)} placeholder="Ej: ORD-1234567890-123" required className="w-full rounded-xl border border-ink-200 bg-cloud-50 px-4 py-3.5 text-sm text-ink-950 placeholder-ink-300 focus:border-signal-500 focus:ring-signal-500/20" /></div><div><label htmlFor="purchase-email" className="mb-2 block text-[10px] font-bold uppercase tracking-widest text-ink-500">Correo de compra</label><input id="purchase-email" type="email" value={data.email} onChange={(event) => setData('email', event.target.value)} placeholder="correo@ejemplo.cl" required className="w-full rounded-xl border border-ink-200 bg-cloud-50 px-4 py-3.5 text-sm text-ink-950 placeholder-ink-300 focus:border-signal-500 focus:ring-signal-500/20" /></div></div><button type="submit" disabled={processing} className="public-button mt-5 w-full disabled:opacity-50">{processing ? 'Consultando…' : 'Consultar estado'}</button></form>
                {order && <div className="mt-8 rounded-3xl border border-ink-100 bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-col justify-between gap-4 border-b border-ink-100 pb-6 sm:flex-row sm:items-center"><div><p className="text-[10px] font-bold uppercase tracking-widest text-ink-400">Orden</p><h2 className="mt-2 text-2xl font-semibold text-ink-950">{order.buy_order}</h2></div><span className="rounded-full bg-signal-50 px-3 py-2 text-[10px] font-bold uppercase tracking-widest text-signal-700">{statusLabels[order.status] || order.status}</span></div><div className="mt-6 space-y-3">{order.items?.map((item) => <div key={item.id} className="flex justify-between gap-4 rounded-xl border border-ink-100 bg-cloud-50 px-4 py-3 text-sm"><span className="text-ink-700">{item.product_name} <span className="text-ink-400">×{item.quantity}</span></span><span className="font-semibold text-ink-950">${Number(item.price * item.quantity).toLocaleString('es-CL')}</span></div>)}</div><div className="mt-6 flex justify-between border-t border-ink-100 pt-5 text-sm"><span className="font-semibold text-ink-500">Total</span><span className="text-lg font-semibold text-ink-950">${Number(order.total_amount).toLocaleString('es-CL')}</span></div></div>}
            </div></section>
        </PublicLayout>
    );
}
