import PublicLayout from '@/Layouts/PublicLayout';
import Breadcrumbs from '@/Components/Breadcrumbs';
import { Head, Link, router } from '@inertiajs/react';
import { useState } from 'react';

const categories = ['noticias', 'guias', 'tecnologia', 'industria'];

export default function BlogIndex({ auth, posts, filters }) {
    const [search, setSearch] = useState(filters.search || '');
    const submit = (event) => { event.preventDefault(); router.get(route('blog.index'), { ...filters, search }, { preserveState: true }); };
    return (
        <PublicLayout auth={auth}><Head><title>Recursos técnicos | Melkerven</title><meta name="description" content="Noticias, guías técnicas y tendencias en hardware de servidores, networking y almacenamiento empresarial." /></Head>
            <section className="relative min-h-screen overflow-hidden bg-cloud-50 py-16 sm:py-20"><div className="public-network absolute inset-0 opacity-60" /><div className="pointer-events-none absolute -left-24 top-0 size-[28rem] rounded-full bg-signal-300/25 blur-[100px]" /><div className="section-shell relative z-10"><Breadcrumbs items={[{ label: 'Blog' }]} /><div className="mt-8 max-w-3xl"><div className="public-eyebrow">Conocimiento técnico</div><h1 className="mt-6 text-5xl font-semibold tracking-[-.06em] text-ink-950 sm:text-7xl">Guías para decidir <span className="text-signal-600">mejor.</span></h1><p className="mt-5 text-lg leading-8 text-ink-600">Contexto práctico para evaluar infraestructura, compatibilidad y ciclos de renovación.</p></div>
                <div className="mt-10 flex flex-col gap-5 border-b border-ink-200 pb-8 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-2"><Link href={route('blog.index')} className={`rounded-xl border px-4 py-2.5 text-[10px] font-bold uppercase tracking-widest ${!filters.category ? 'border-ink-950 bg-ink-950 text-white' : 'border-ink-200 bg-white text-ink-600 hover:border-signal-400'}`}>Todos</Link>{categories.map((category) => <Link key={category} href={route('blog.index', { category })} className={`rounded-xl border px-4 py-2.5 text-[10px] font-bold uppercase tracking-widest capitalize ${filters.category === category ? 'border-ink-950 bg-ink-950 text-white' : 'border-ink-200 bg-white text-ink-600 hover:border-signal-400'}`}>{category}</Link>)}</div><form onSubmit={submit} className="relative w-full lg:w-80"><label htmlFor="blog-search" className="sr-only">Buscar artículo</label><input id="blog-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar artículo..." className="w-full rounded-xl border border-ink-200 bg-white py-3 pl-4 pr-20 text-sm text-ink-950 placeholder-ink-300 focus:border-signal-500 focus:ring-signal-500/20" /><button type="submit" className="absolute right-2 top-1/2 -translate-y-1/2 rounded-lg bg-ink-950 px-3 py-2 text-[10px] font-bold uppercase tracking-widest text-white">Buscar</button></form></div>
                {posts.data.length === 0 ? <div className="mt-10 rounded-3xl border border-ink-100 bg-white p-12 text-center shadow-[0_15px_36px_rgba(31,62,82,.07)]"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-signal-700">Centro de recursos</p><h2 className="mt-4 text-3xl font-semibold text-ink-950">Estamos preparando contenido técnico útil.</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-7 text-ink-500">Mientras publicamos guías, puede revisar las preguntas frecuentes o enviarnos un requerimiento específico para orientarlo directamente.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Link href={route('faq')} className="public-button-secondary">Ver preguntas frecuentes</Link><Link href={route('contact')} className="public-button">Hacer una consulta</Link></div></div> : <div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{posts.data.map((post) => <Link key={post.id} href={route('blog.show', post.slug)} className="group overflow-hidden rounded-3xl border border-ink-100 bg-white p-4 shadow-sm transition hover:-translate-y-1 hover:border-signal-300"><div className="flex h-48 items-center justify-center overflow-hidden rounded-2xl bg-cloud-50">{post.image_url ? <img src={post.image_url} alt={post.title} className="size-full object-cover transition duration-700 group-hover:scale-105" loading="lazy" /> : <span className="text-4xl text-signal-400">⌁</span>}</div><p className="mt-5 text-[10px] font-bold uppercase tracking-widest text-signal-700">{post.category}</p><h2 className="mt-2 line-clamp-2 text-xl font-semibold text-ink-950">{post.title}</h2><p className="mt-3 line-clamp-3 text-sm leading-6 text-ink-500">{post.excerpt}</p></Link>)}</div>}
            </div></section>
        </PublicLayout>
    );
}
